"""change facilities model

Revision ID: 4d39bc78466c
Revises: 41f24644bfc9
Create Date: 2026-03-06 11:58:39.961602

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4d39bc78466c"
down_revision: Union[str, Sequence[str], None] = "41f24644bfc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
