"""change rooms model

Revision ID: f066a9a34a77
Revises: ad14850314db
Create Date: 2026-03-04 13:07:46.876493

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "f066a9a34a77"
down_revision: Union[str, Sequence[str], None] = "ad14850314db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
