"""add column created_at in bookings model

Revision ID: 44c9d1f15ba0
Revises: dfb318fe3fec
Create Date: 2026-03-05 11:18:26.766823

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "44c9d1f15ba0"
down_revision: Union[str, Sequence[str], None] = "dfb318fe3fec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
